// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrszK9-YmuABg5c4YeXe1VxiSXUeJogo4',
    appId: '1:988235484724:web:3551e01cfddcf1ea510461',
    messagingSenderId: '988235484724',
    projectId: 'purple-core-server',
    authDomain: 'purple-core-server.firebaseapp.com',
    storageBucket: 'purple-core-server.firebasestorage.app',
    measurementId: 'G-CB67YMLYR5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrszK9-YmuABg5c4YeXe1VxiSXUeJogo4',
    appId: '1:988235484724:web:b16d5aa0e70a75c9510461',
    messagingSenderId: '988235484724',
    projectId: 'purple-core-server',
    authDomain: 'purple-core-server.firebaseapp.com',
    storageBucket: 'purple-core-server.firebasestorage.app',
    measurementId: 'G-4XCKHYGDKT',
  );
}
